function build_models(params)
%BUILD_MODELS Create the educational Simulink models.
%
% The function creates model binaries only when run locally in MATLAB with
% Simulink installed. Existing files are left untouched.

if nargin < 1
    params = init_params();
end

if exist(params.model_files.sensor_dynamics, 'file') ~= 2
    local_build_sensor_dynamics(params);
else
    warning('build_models:ExistingDynamics', ...
        'Keeping existing model: %s', params.model_files.sensor_dynamics);
end

if exist(params.model_files.signal_chain, 'file') ~= 2
    local_build_signal_chain(params);
else
    warning('build_models:ExistingSignalChain', ...
        'Keeping existing model: %s', params.model_files.signal_chain);
end

if exist(params.model_files.capacitive_chain, 'file') ~= 2
    local_build_capacitive_chain(params);
else
    warning('build_models:ExistingCapacitiveChain', ...
        'Keeping existing model: %s', params.model_files.capacitive_chain);
end

if exist(params.model_files.readout_frontend, 'file') ~= 2
    local_build_readout_frontend(params);
else
    warning('build_models:ExistingReadoutFrontend', ...
        'Keeping existing model: %s', params.model_files.readout_frontend);
end

if exist(params.model_files.codegen, 'file') ~= 2
    local_build_codegen_discrete(params);
else
    warning('build_models:ExistingCodegenModel', ...
        'Keeping existing model: %s', params.model_files.codegen);
end

end

function local_build_sensor_dynamics(params)
model_name = 'sensor_dynamics';
model_file = params.model_files.sensor_dynamics;
local_prepare_model_folder(model_file);
local_close_partial_model(model_name);

new_system(model_name);
set_param(model_name, 'Solver', 'ode45', ...
    'RelTol', '1e-6', 'AbsTol', '1e-8', ...
    'StopTime', num2str(params.tfinal));

local_add_step(model_name, 'u_step', params);
local_add_state_space(model_name, 'mechanical_dynamics', params);
add_block('simulink/Signal Routing/Demux', ...
    [model_name '/state_demux'], 'Outputs', '2', ...
    'Position', [390 85 420 145]);
add_block('simulink/Sinks/Out1', [model_name '/x'], ...
    'Position', [500 80 530 100]);
add_block('simulink/Sinks/Out1', [model_name '/y'], ...
    'Position', [500 130 530 150]);
local_add_to_workspace(model_name, 'log_x', 'x_sim', [585 75 700 105]);
local_add_to_workspace(model_name, 'log_y', 'y_sim', [585 125 700 155]);

add_line(model_name, 'u_step/1', 'mechanical_dynamics/1');
add_line(model_name, 'mechanical_dynamics/1', 'state_demux/1');
add_line(model_name, 'state_demux/1', 'x/1');
add_line(model_name, 'state_demux/2', 'y/1');
add_line(model_name, 'state_demux/1', 'log_x/1');
add_line(model_name, 'state_demux/2', 'log_y/1');

save_system(model_name, model_file);
close_system(model_name, 0);
end

function local_build_readout_frontend(params)
% Build the ideal capacitive readout and mixed-signal front-end model.
model_name = 'sensor_readout_frontend';
model_file = params.model_files.readout_frontend;
local_prepare_model_folder(model_file);
local_close_partial_model(model_name);

new_system(model_name);
set_param(model_name, 'Solver', 'ode45', ...
    'RelTol', '1e-6', 'AbsTol', '1e-8', ...
    'StopTime', num2str(params.tfinal));

local_add_step(model_name, 'u_step', params);
local_add_state_space(model_name, 'mechanical_dynamics', params);
add_block('simulink/Signal Routing/Demux', ...
    [model_name '/state_demux'], 'Outputs', '2', ...
    'Position', [390 80 420 140]);

% Differential capacitive transducer.
add_block('simulink/Math Operations/Gain', ...
    [model_name '/displacement_scale'], ...
    'Gain', num2str(params.capacitance.displacement_scale), ...
    'Position', [465 55 555 85]);
add_block('simulink/Sources/Constant', [model_name '/gap_for_c1'], ...
    'Value', num2str(params.capacitance.gap), ...
    'Position', [465 150 540 180]);
add_block('simulink/Sources/Constant', [model_name '/gap_for_c2'], ...
    'Value', num2str(params.capacitance.gap), ...
    'Position', [465 235 540 265]);
add_block('simulink/Math Operations/Sum', ...
    [model_name '/gap_minus_xi'], 'Inputs', '+-', ...
    'Position', [590 90 620 130]);
add_block('simulink/Math Operations/Sum', ...
    [model_name '/gap_plus_xi'], 'Inputs', '++', ...
    'Position', [590 220 620 260]);
add_block('simulink/Math Operations/Math Function', ...
    [model_name '/reciprocal_c1'], 'Operator', 'reciprocal', ...
    'Position', [655 90 720 130]);
add_block('simulink/Math Operations/Math Function', ...
    [model_name '/reciprocal_c2'], 'Operator', 'reciprocal', ...
    'Position', [655 220 720 260]);
add_block('simulink/Math Operations/Gain', [model_name '/epsilon_area_c1'], ...
    'Gain', num2str(params.capacitance.epsilon * ...
    params.capacitance.electrode_area), ...
    'Position', [755 90 845 130]);
add_block('simulink/Math Operations/Gain', [model_name '/epsilon_area_c2'], ...
    'Gain', num2str(params.capacitance.epsilon * ...
    params.capacitance.electrode_area), ...
    'Position', [755 220 845 260]);
add_block('simulink/Math Operations/Sum', [model_name '/delta_c'], ...
    'Inputs', '+-', 'Position', [880 145 910 195]);
add_block('simulink/Math Operations/Gain', ...
    [model_name '/cv_converter'], ...
    'Gain', num2str(params.readout.gain_v_per_f), ...
    'Position', [945 150 1040 190]);

% Offset, noise, finite bandwidth, and analogue saturation.
add_block('simulink/Sources/Constant', [model_name '/offset_voltage'], ...
    'Value', num2str(params.readout.offset_voltage), ...
    'Position', [1045 235 1120 265]);
add_block('simulink/Math Operations/Sum', [model_name '/add_offset'], ...
    'Inputs', '++', 'Position', [1150 145 1180 195]);
add_block('simulink/Sources/Random Number', [model_name '/amplifier_noise'], ...
    'Mean', '0', ...
    'Variance', num2str(params.readout.noise_amplitude^2), ...
    'Seed', num2str(params.readout.noise_seed), 'SampleTime', '0.01', ...
    'Position', [1140 285 1220 325]);
add_block('simulink/Math Operations/Sum', [model_name '/add_noise'], ...
    'Inputs', '++', 'Position', [1250 150 1280 200]);
add_block('simulink/Continuous/Transfer Fcn', ...
    [model_name '/frontend_bandwidth'], 'Numerator', '[1]', ...
    'Denominator', sprintf('[%g 1]', params.readout.bandwidth_tau), ...
    'Position', [1320 155 1410 195]);
add_block('simulink/Discontinuities/Saturation', ...
    [model_name '/amplifier_saturation'], ...
    'UpperLimit', num2str(params.readout.amplifier_max), ...
    'LowerLimit', num2str(params.readout.amplifier_min), ...
    'Position', [1450 155 1530 195]);

% ADC: voltage scaling, unit-step quantization, reconstruction, and
% digital conversion back to normalized displacement.
adc_levels = 2^params.readout.adc_bits;
adc_scale = (adc_levels - 1) / ...
    (params.readout.adc_max - params.readout.adc_min);
adc_lsb = (params.readout.adc_max - params.readout.adc_min) / ...
    (adc_levels - 1);
add_block('simulink/Discontinuities/Saturation', ...
    [model_name '/adc_input_saturation'], ...
    'UpperLimit', num2str(params.readout.adc_max), ...
    'LowerLimit', num2str(params.readout.adc_min), ...
    'Position', [1570 155 1650 195]);
add_block('simulink/Math Operations/Gain', [model_name '/adc_scale'], ...
    'Gain', num2str(adc_scale), 'Position', [1690 155 1770 195]);
add_block('simulink/Discontinuities/Quantizer', [model_name '/adc_quantizer'], ...
    'QuantizationInterval', '1', 'Position', [1810 155 1890 195]);
add_block('simulink/Math Operations/Gain', [model_name '/adc_lsb'], ...
    'Gain', num2str(adc_lsb), 'Position', [1930 155 2010 195]);
add_block('simulink/Sources/Constant', [model_name '/adc_min'], ...
    'Value', num2str(params.readout.adc_min), ...
    'Position', [1930 235 2010 265]);
add_block('simulink/Math Operations/Sum', [model_name '/adc_voltage'], ...
    'Inputs', '++', 'Position', [2050 155 2080 205]);
add_block('simulink/Sources/Constant', [model_name '/offset_estimate'], ...
    'Value', num2str(params.readout.offset_estimate), ...
    'Position', [2050 275 2130 305]);
add_block('simulink/Math Operations/Sum', ...
    [model_name '/subtract_offset_estimate'], ...
    'Inputs', '+-', 'Position', [2170 155 2200 205]);
add_block('simulink/Math Operations/Gain', ...
    [model_name '/digital_calibration'], ...
    'Gain', num2str(1 ./ (params.readout.gain_v_per_f .* ...
    params.capacitance.sensitivity .* ...
    params.capacitance.displacement_scale)), ...
    'Position', [2240 165 2340 205]);
add_block('simulink/Sinks/Out1', [model_name '/calibrated_displacement'], ...
    'Position', [2380 175 2410 195]);

local_add_to_workspace(model_name, 'log_x', 'x_frontend_sim', ...
    [465 370 580 400]);
local_add_to_workspace(model_name, 'log_delta_c', 'delta_c_frontend_sim', ...
    [760 370 875 400]);
local_add_to_workspace(model_name, 'log_amplifier', 'v_amplifier_sim', ...
    [1300 370 1420 400]);
local_add_to_workspace(model_name, 'log_adc', 'adc_code_sim', ...
    [1800 370 1915 400]);
local_add_to_workspace(model_name, 'log_calibrated', ...
    'x_calibrated_sim', [2240 370 2360 400]);

add_line(model_name, 'u_step/1', 'mechanical_dynamics/1');
add_line(model_name, 'mechanical_dynamics/1', 'state_demux/1');
add_line(model_name, 'state_demux/1', 'displacement_scale/1');
add_line(model_name, 'state_demux/1', 'log_x/1');
add_line(model_name, 'displacement_scale/1', 'gap_minus_xi/2');
add_line(model_name, 'displacement_scale/1', 'gap_plus_xi/2');
add_line(model_name, 'gap_for_c1/1', 'gap_minus_xi/1');
add_line(model_name, 'gap_for_c2/1', 'gap_plus_xi/1');
add_line(model_name, 'gap_minus_xi/1', 'reciprocal_c1/1');
add_line(model_name, 'gap_plus_xi/1', 'reciprocal_c2/1');
add_line(model_name, 'reciprocal_c1/1', 'epsilon_area_c1/1');
add_line(model_name, 'reciprocal_c2/1', 'epsilon_area_c2/1');
add_line(model_name, 'epsilon_area_c1/1', 'delta_c/1');
add_line(model_name, 'epsilon_area_c2/1', 'delta_c/2');
add_line(model_name, 'delta_c/1', 'cv_converter/1');
add_line(model_name, 'delta_c/1', 'log_delta_c/1');
add_line(model_name, 'cv_converter/1', 'add_offset/1');
add_line(model_name, 'offset_voltage/1', 'add_offset/2');
add_line(model_name, 'add_offset/1', 'add_noise/1');
add_line(model_name, 'amplifier_noise/1', 'add_noise/2');
add_line(model_name, 'add_noise/1', 'frontend_bandwidth/1');
add_line(model_name, 'frontend_bandwidth/1', 'amplifier_saturation/1');
add_line(model_name, 'amplifier_saturation/1', 'adc_input_saturation/1');
add_line(model_name, 'amplifier_saturation/1', 'log_amplifier/1');
add_line(model_name, 'adc_input_saturation/1', 'adc_scale/1');
add_line(model_name, 'adc_scale/1', 'adc_quantizer/1');
add_line(model_name, 'adc_quantizer/1', 'adc_lsb/1');
add_line(model_name, 'adc_quantizer/1', 'log_adc/1');
add_line(model_name, 'adc_lsb/1', 'adc_voltage/1');
add_line(model_name, 'adc_min/1', 'adc_voltage/2');
add_line(model_name, 'adc_voltage/1', 'subtract_offset_estimate/1');
add_line(model_name, 'offset_estimate/1', 'subtract_offset_estimate/2');
add_line(model_name, 'subtract_offset_estimate/1', 'digital_calibration/1');
add_line(model_name, 'digital_calibration/1', 'calibrated_displacement/1');
add_line(model_name, 'digital_calibration/1', 'log_calibrated/1');

save_system(model_name, model_file);
close_system(model_name, 0);
end

function local_build_capacitive_chain(params)
% Build a signal-chain variant with exact differential-capacitance blocks.
model_name = 'sensor_capacitive_chain';
model_file = params.model_files.capacitive_chain;
local_prepare_model_folder(model_file);
local_close_partial_model(model_name);

new_system(model_name);
set_param(model_name, 'Solver', 'ode45', ...
    'RelTol', '1e-6', 'AbsTol', '1e-8', ...
    'StopTime', num2str(params.tfinal));

local_add_step(model_name, 'u_step', params);
local_add_state_space(model_name, 'mechanical_dynamics', params);
add_block('simulink/Signal Routing/Demux', ...
    [model_name '/state_demux'], 'Outputs', '2', ...
    'Position', [390 80 420 140]);

% xi = displacement_scale*x, then C1 = eps*A/(d-xi) and
% C2 = eps*A/(d+xi).
add_block('simulink/Math Operations/Gain', ...
    [model_name '/displacement_scale'], ...
    'Gain', num2str(params.capacitance.displacement_scale), ...
    'Position', [465 55 555 85]);
add_block('simulink/Sources/Constant', [model_name '/gap_for_c1'], ...
    'Value', num2str(params.capacitance.gap), ...
    'Position', [465 150 540 180]);
add_block('simulink/Sources/Constant', [model_name '/gap_for_c2'], ...
    'Value', num2str(params.capacitance.gap), ...
    'Position', [465 235 540 265]);
add_block('simulink/Math Operations/Sum', ...
    [model_name '/gap_minus_xi'], 'Inputs', '+-', ...
    'Position', [590 90 620 130]);
add_block('simulink/Math Operations/Sum', ...
    [model_name '/gap_plus_xi'], 'Inputs', '++', ...
    'Position', [590 220 620 260]);
add_block('simulink/Math Operations/Math Function', ...
    [model_name '/reciprocal_c1'], 'Operator', 'reciprocal', ...
    'Position', [655 90 720 130]);
add_block('simulink/Math Operations/Math Function', ...
    [model_name '/reciprocal_c2'], 'Operator', 'reciprocal', ...
    'Position', [655 220 720 260]);
add_block('simulink/Math Operations/Gain', [model_name '/epsilon_area_c1'], ...
    'Gain', num2str(params.capacitance.epsilon * ...
    params.capacitance.electrode_area), ...
    'Position', [755 90 845 130]);
add_block('simulink/Math Operations/Gain', [model_name '/epsilon_area_c2'], ...
    'Gain', num2str(params.capacitance.epsilon * ...
    params.capacitance.electrode_area), ...
    'Position', [755 220 845 260]);
add_block('simulink/Math Operations/Sum', [model_name '/delta_c'], ...
    'Inputs', '+-', 'Position', [880 145 910 195]);
add_block('simulink/Math Operations/Gain', ...
    [model_name '/capacitive_readout'], ...
    'Gain', num2str(params.capacitance.readout_gain), ...
    'Position', [945 150 1040 190]);
add_block('simulink/Sinks/Out1', [model_name '/calibrated_output'], ...
    'Position', [1390 165 1420 185]);

% The remainder is the same bias/noise/filter/calibration chain as the
% existing signal-chain model.
add_block('simulink/Sources/Constant', [model_name '/bias'], ...
    'Value', num2str(params.bias), 'Position', [1050 230 1120 260]);
add_block('simulink/Math Operations/Sum', [model_name '/add_bias'], ...
    'Inputs', '++', 'Position', [1150 145 1180 195]);
add_block('simulink/Sources/Random Number', [model_name '/measurement_noise'], ...
    'Mean', '0', 'Variance', num2str(params.noise_amplitude^2), ...
    'Seed', num2str(params.noise_seed), 'SampleTime', '0.01', ...
    'Position', [1140 280 1220 320]);
add_block('simulink/Math Operations/Sum', [model_name '/add_noise'], ...
    'Inputs', '++', 'Position', [1250 150 1280 200]);
add_block('simulink/Continuous/Transfer Fcn', [model_name '/lowpass'], ...
    'Numerator', '[1]', 'Denominator', sprintf('[%g 1]', params.lowpass_tau), ...
    'Position', [1320 155 1400 195]);
add_block('simulink/Sources/Constant', [model_name '/bias_estimate'], ...
    'Value', num2str(params.bias_estimate), ...
    'Position', [1320 250 1400 280]);
add_block('simulink/Math Operations/Sum', [model_name '/subtract_bias'], ...
    'Inputs', '+-', 'Position', [1450 155 1480 205]);
add_block('simulink/Math Operations/Gain', [model_name '/calibration_scale'], ...
    'Gain', num2str(params.calibration_scale), ...
    'Position', [1520 165 1600 205]);

local_add_to_workspace(model_name, 'log_x', 'x_cap_sim', [465 370 580 400]);
local_add_to_workspace(model_name, 'log_delta_c', 'delta_c_sim', ...
    [760 370 875 400]);
local_add_to_workspace(model_name, 'log_raw', 'v_raw_cap_sim', ...
    [1080 370 1195 400]);
local_add_to_workspace(model_name, 'log_filtered', ...
    'v_filtered_cap_sim', [1300 370 1420 400]);
local_add_to_workspace(model_name, 'log_calibrated', ...
    'calibrated_cap_sim', [1510 370 1640 400]);

add_line(model_name, 'u_step/1', 'mechanical_dynamics/1');
add_line(model_name, 'mechanical_dynamics/1', 'state_demux/1');
add_line(model_name, 'state_demux/1', 'displacement_scale/1');
add_line(model_name, 'state_demux/1', 'log_x/1');
add_line(model_name, 'displacement_scale/1', 'gap_minus_xi/2');
add_line(model_name, 'displacement_scale/1', 'gap_plus_xi/2');
add_line(model_name, 'gap_for_c1/1', 'gap_minus_xi/1');
add_line(model_name, 'gap_for_c2/1', 'gap_plus_xi/1');
add_line(model_name, 'gap_minus_xi/1', 'reciprocal_c1/1');
add_line(model_name, 'gap_plus_xi/1', 'reciprocal_c2/1');
add_line(model_name, 'reciprocal_c1/1', 'epsilon_area_c1/1');
add_line(model_name, 'reciprocal_c2/1', 'epsilon_area_c2/1');
add_line(model_name, 'epsilon_area_c1/1', 'delta_c/1');
add_line(model_name, 'epsilon_area_c2/1', 'delta_c/2');
add_line(model_name, 'delta_c/1', 'capacitive_readout/1');
add_line(model_name, 'delta_c/1', 'log_delta_c/1');
add_line(model_name, 'capacitive_readout/1', 'add_bias/1');
add_line(model_name, 'bias/1', 'add_bias/2');
add_line(model_name, 'add_bias/1', 'add_noise/1');
add_line(model_name, 'measurement_noise/1', 'add_noise/2');
add_line(model_name, 'add_noise/1', 'lowpass/1');
add_line(model_name, 'add_noise/1', 'log_raw/1');
add_line(model_name, 'lowpass/1', 'subtract_bias/1');
add_line(model_name, 'lowpass/1', 'log_filtered/1');
add_line(model_name, 'bias_estimate/1', 'subtract_bias/2');
add_line(model_name, 'subtract_bias/1', 'calibration_scale/1');
add_line(model_name, 'calibration_scale/1', 'calibrated_output/1');
add_line(model_name, 'calibration_scale/1', 'log_calibrated/1');

save_system(model_name, model_file);
close_system(model_name, 0);
end

function local_build_signal_chain(params)
model_name = 'sensor_signal_chain';
model_file = params.model_files.signal_chain;
local_prepare_model_folder(model_file);
local_close_partial_model(model_name);

new_system(model_name);
set_param(model_name, 'Solver', 'ode45', ...
    'RelTol', '1e-6', 'AbsTol', '1e-8', ...
    'StopTime', num2str(params.tfinal));

local_add_step(model_name, 'u_step', params);
local_add_state_space(model_name, 'mechanical_dynamics', params);
add_block('simulink/Signal Routing/Demux', ...
    [model_name '/state_demux'], 'Outputs', '2', ...
    'Position', [390 80 420 140]);
add_block('simulink/Math Operations/Gain', [model_name '/transduction_gain'], ...
    'Gain', num2str(params.transduction_gain), ...
    'Position', [470 70 540 100]);
add_block('simulink/Sources/Constant', [model_name '/bias'], ...
    'Value', num2str(params.bias), 'Position', [470 160 540 190]);
add_block('simulink/Math Operations/Sum', [model_name '/add_bias'], ...
    'Inputs', '++', 'Position', [590 75 620 125]);
add_block('simulink/Sources/Random Number', [model_name '/measurement_noise'], ...
    'Mean', '0', ...
    'Variance', num2str(params.noise_amplitude^2), ...
    'Seed', num2str(params.noise_seed), 'SampleTime', '0.01', ...
    'Position', [580 170 660 210]);
add_block('simulink/Math Operations/Sum', [model_name '/add_noise'], ...
    'Inputs', '++', 'Position', [710 80 740 130]);
add_block('simulink/Continuous/Transfer Fcn', [model_name '/lowpass'], ...
    'Numerator', '[1]', ...
    'Denominator', sprintf('[%g 1]', params.lowpass_tau), ...
    'Position', [790 85 880 125]);
add_block('simulink/Sources/Constant', [model_name '/bias_estimate'], ...
    'Value', num2str(params.bias_estimate), ...
    'Position', [790 170 880 200]);
add_block('simulink/Math Operations/Sum', [model_name '/subtract_bias'], ...
    'Inputs', '+-', 'Position', [930 85 960 135]);
add_block('simulink/Math Operations/Gain', [model_name '/calibration_scale'], ...
    'Gain', num2str(params.calibration_scale), ...
    'Position', [1000 90 1080 130]);
add_block('simulink/Sinks/Out1', [model_name '/calibrated_output'], ...
    'Position', [1130 95 1160 115]);

local_add_to_workspace(model_name, 'log_x', 'x_sim', [470 255 585 285]);
local_add_to_workspace(model_name, 'log_raw', 'v_raw_sim', [770 255 885 285]);
local_add_to_workspace(model_name, 'log_filtered', ...
    'v_filtered_sim', [920 255 1040 285]);
local_add_to_workspace(model_name, 'log_calibrated', ...
    'calibrated_output_sim', [1090 255 1230 285]);

add_line(model_name, 'u_step/1', 'mechanical_dynamics/1');
add_line(model_name, 'mechanical_dynamics/1', 'state_demux/1');
add_line(model_name, 'state_demux/1', 'transduction_gain/1');
add_line(model_name, 'state_demux/1', 'log_x/1');
add_line(model_name, 'transduction_gain/1', 'add_bias/1');
add_line(model_name, 'bias/1', 'add_bias/2');
add_line(model_name, 'add_bias/1', 'add_noise/1');
add_line(model_name, 'measurement_noise/1', 'add_noise/2');
add_line(model_name, 'add_noise/1', 'lowpass/1');
add_line(model_name, 'add_noise/1', 'log_raw/1');
add_line(model_name, 'lowpass/1', 'subtract_bias/1');
add_line(model_name, 'lowpass/1', 'log_filtered/1');
add_line(model_name, 'bias_estimate/1', 'subtract_bias/2');
add_line(model_name, 'subtract_bias/1', 'calibration_scale/1');
add_line(model_name, 'calibration_scale/1', 'calibrated_output/1');
add_line(model_name, 'calibration_scale/1', 'log_calibrated/1');

save_system(model_name, model_file);
close_system(model_name, 0);
end

function local_build_codegen_discrete(params)
% Build a fixed-step discrete model suitable for Simulink Coder.
model_name = 'sensor_codegen_discrete';
model_file = params.model_files.codegen;
local_prepare_model_folder(model_file);
local_close_partial_model(model_name);

new_system(model_name);
set_param(model_name, 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(params.codegen.sample_time), ...
    'StopTime', num2str(params.tfinal), ...
    'SaveOutput', 'off', ...
    'SaveTime', 'off', ...
    'SaveState', 'off', ...
    'SaveFinalState', 'off', ...
    'SignalLogging', 'off', ...
    'DSMLogging', 'off');

matrices = discretize_sensor_model(params.k, params.r, ...
    params.codegen.sample_time);

add_block('simulink/Sources/Step', [model_name '/u_step'], ...
    'Time', num2str(params.input.step_time), ...
    'Before', num2str(params.input.before), ...
    'After', num2str(params.input.after), ...
    'SampleTime', num2str(params.codegen.sample_time), ...
    'Position', [35 95 90 125]);

add_block('simulink/Discrete/Discrete State-Space', ...
    [model_name '/discrete_mechanics'], ...
    'A', mat2str(matrices.Ad, 16), ...
    'B', mat2str(matrices.Bd, 16), ...
    'C', '[1 0; 0 1]', ...
    'D', '[0; 0]', ...
    'X0', sprintf('[%g; %g]', params.x0, params.y0), ...
    'SampleTime', num2str(params.codegen.sample_time), ...
    'Position', [145 80 350 140]);
add_block('simulink/Signal Routing/Demux', ...
    [model_name '/state_demux'], 'Outputs', '2', ...
    'Position', [410 85 440 145]);
add_block('simulink/Sinks/Out1', [model_name '/x'], ...
    'Position', [520 80 550 100]);
add_block('simulink/Sinks/Out1', [model_name '/y'], ...
    'Position', [520 130 550 150]);

add_line(model_name, 'u_step/1', 'discrete_mechanics/1');
add_line(model_name, 'discrete_mechanics/1', 'state_demux/1');
add_line(model_name, 'state_demux/1', 'x/1');
add_line(model_name, 'state_demux/2', 'y/1');

save_system(model_name, model_file);
close_system(model_name, 0);
end

function local_add_step(model_name, block_name, params)
add_block('simulink/Sources/Step', [model_name '/' block_name], ...
    'Time', num2str(params.input.step_time), ...
    'Before', num2str(params.input.before), ...
    'After', num2str(params.input.after), ...
    'Position', [35 95 90 125]);
end

function local_add_state_space(model_name, block_name, params)
add_block('simulink/Continuous/State-Space', ...
    [model_name '/' block_name], ...
    'A', sprintf('[0 1; -%g -%g]', params.k, params.r), ...
    'B', '[0; 1]', 'C', '[1 0; 0 1]', 'D', '[0; 0]', ...
    'X0', sprintf('[%g; %g]', params.x0, params.y0), ...
    'Position', [145 80 330 140]);
end

function local_add_to_workspace(model_name, block_name, variable_name, position)
add_block('simulink/Sinks/To Workspace', [model_name '/' block_name], ...
    'VariableName', variable_name, 'SaveFormat', 'Timeseries', ...
    'Position', position);
end

function local_prepare_model_folder(model_file)
model_folder = fileparts(model_file);
if exist(model_folder, 'dir') ~= 7
    mkdir(model_folder);
end
end

function local_close_partial_model(model_name)
% A failed build can leave an unsaved model loaded in memory.
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
